# Generated by Django 3.2.8 on 2021-10-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodytypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytype', models.CharField(max_length=100, verbose_name='Тип кузова')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Gears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(max_length=100, verbose_name='Привод')),
            ],
        ),
        migrations.CreateModel(
            name='Rudders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rudder', models.CharField(max_length=100, verbose_name='Руль')),
            ],
        ),
        migrations.CreateModel(
            name='Transmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=100, verbose_name='Трансмиссия')),
            ],
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('power', models.CharField(max_length=100, verbose_name='Мощность')),
                ('mileage', models.CharField(max_length=100, verbose_name='Пробег')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('bodytype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autos.bodytypes', verbose_name='Тип кузова')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autos.colors', verbose_name='Цвет')),
                ('gear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autos.gears', verbose_name='Привод')),
                ('rudder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autos.rudders', verbose_name='Руль')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='autos.transmissions', verbose_name='Трансмиссия')),
            ],
        ),
    ]
