# Generated by Django 3.2.8 on 2021-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autos',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='bodytypes',
            options={'verbose_name': 'Кузов', 'verbose_name_plural': 'Кузова'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='gears',
            options={'verbose_name': 'Привод', 'verbose_name_plural': 'Привода'},
        ),
        migrations.AlterModelOptions(
            name='rudders',
            options={'verbose_name': 'Руль', 'verbose_name_plural': 'Рули'},
        ),
        migrations.AlterModelOptions(
            name='transmissions',
            options={'verbose_name': 'Трансмиссия', 'verbose_name_plural': 'Трансмиссии'},
        ),
        migrations.AddField(
            model_name='autos',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='autos',
            name='year',
            field=models.CharField(max_length=100, null=True, verbose_name='Год выпуска'),
        ),
    ]
