# Generated by Django 3.2.8 on 2021-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20211027_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
